homeassistant:
  # Name of the location where Home Assistant is running
  # very creative, I know
  name: Home
  # Location required to calculate the time the sun rises and sets
  # Location information is kept secret ;)
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Berlin
  # Load packages (split-configuration format)
  # Note: Only set up components there
  packages: !include_dir_named components
  # Lets me customize individual entities
  customize: !include_dir_merge_named customizations
  # Lets me customize all entities in a domain
  customize_domain: !include_dir_merge_named customizations_domains
  # Lets me custimize entities based on a matching pattern
  customize_glob: !include_dir_merge_named customizations_globs

# More complex configurations are stored in directories:
automation: !include_dir_merge_list automations
binary_sensor: !include_dir_merge_list binary_sensors
device_tracker: !include_dir_merge_list device_trackers
group: !include_dir_merge_named groups
input_boolean: !include_dir_merge_named input_booleans
input_number: !include_dir_merge_named input_numbers
input_select: !include_dir_merge_named input_selects
#light: !include_dir_merge_list lights
plant: !include_dir_merge_named plants
python_script:
rest_command: !include_dir_merge_named rest_commands
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches


#TODO: Move existing settings from
# - packages
# - floorplan.yaml
